### ISSUE TITLE
Add Simple Mode

### ISSUE THREAD

**Issue by thejacko12354** [mtongnz/ESP8266_ArtNetNode_v2#75]
First of all Great Project, I really like it!
It would be even better if there was something like a simple mode where you only have like 4 channels or so (brightness, red, green, blue) and a start address. Which controll all leds at once. So you could build for example 10 small table-lights and only use like 40 channels in one universe.
That would be really great.

Greets Jacko

**Comment by mtongnz** [comment]
This is available using the FX mode - it uses 12 channels rather than 4 but gives heaps more functionality by allowing effects to be run.  Feel free to change it if you want it different but I see no point making it with less channels.  If you're after pure RGB control for the entire strip, I'd recommend using RGB tape as it's cheaper and easier than pixel tape.  I've got another Git with details for a DMX controller for RGB tape.
